#Legal command codes
# CMD_PING_QUERY    = 1,  #// timestamp exchange
# CMD_SET_SONAR_SEQ = 3,  #// up to 24 bytes. unused bytes are 0xff
# CMD_SONAR_STOP    = 4,  #// Stop Ultrasound sensors
# CMD_SONAR_START   = 5,  #// Start Ultrasound sensors
# CMD_WHEEL_RESET   = 8,  #// Clear odometer
# CMD_GET_COUNTERS  = 10, #// Ask teensy to send all non-zero counters
# CMD_SONAR_WAIT    = 12, #// Set waiting time between sonar pings in ms
uint8 command
uint8[] sequence
---
#result
uint32 return
